version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: G@dfwnjq787724!
      POSTGRES_DB: ai_agent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./BE
    container_name: ai_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./BE/.env
    environment:
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - ./BE:/app

  frontend:
    build:
      context: ./FE
    container_name: ai_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
