version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ai_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: G@dfwnjq787724!
      POSTGRES_DB: ai_agent_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ai_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
